theme: jekyll-theme-architect

title: [Web Site Template]
description: [Generic Site Template for Java EE related projects]

# sidebar links url
links:
  download: https://github.com/javaee/website-template/tree/gh-pages
  source: https://github.com/javaee/website-template
  license: LICENSE
  issues_url: site.github.issues_url # project's issue tracker
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:

