theme: jekyll-theme-architect

title: [Web Site Template]
description: [Generic Site Template for Java EE related projects]

enable_issuetracker_link: true #enable the sidebar issue tracker link 

# sidebar links url
links:
  download: https://github.com/javaee/website-template/tree/gh-pages
  source: https://github.com/javaee/website-template
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

