theme: jekyll-theme-architect

title: [Web Site Template]
description: [Generic Site Template for Java EE related projects]


links:
  download: https://github.com/javaee/website-template/tree/gh-pages
  #mailinglist: https://java.net/projects/glassfish/lists/users/archive
  source: https://github.com/javaee/website-template
  license: LICENSE

